apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  # Multi-source: Helm chart + values from Git
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.11.3
      helm:
        valueFiles:
          - $values/platform/nginx-ingress/values.yaml
    
    - repoURL: https://github.com/mmrajput/kubernetes-homelab-01
      targetRevision: HEAD
      ref: values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  
  syncPolicy:
    automated:
      prune: false      # Safety: don't auto-delete
      selfHeal: true    # Auto-revert manual changes
    syncOptions:
      - CreateNamespace=true
